# Make sure to read the comments before configuring! It'll be a big help.

# Glitch patches
patcher:
  # If enabled: Toggles vanish off if you're vanished. (Essentials)
  fix-vanish: false

  # If enabled: Patches player returning to arena using /back after the match. (Essentials)
  fix-back: true

  # If enabled: Disables teleporting to players in match. This was implemented due to the following exploit:
  # 1) Player 1 sends a duel request to player 2.
  # 2) Player 3 sends /tpa to Player 1.
  # 3) Player 1 types /tpaccept (Lets assume there's a 5 second delay)
  # 4) Player 2 types /duel accept, and player 1 & player 2 teleports to the arena.
  # 5) Player 3 will be teleported into the arena after 5 seconds, to player 1.
  # 6) The Exploit: Player 3 can now pick up duel kit items
  # Players with OP or the permission 'duels.admin' will bypass this function.
  fix-teleport: true

  # If enabled: Blocks opening of another inventory while in duel.
  # This prevents people exploiting trading systems and such.
  fix-inventory-open: true

# Countdown settings
countdown:
  enabled: true

  # Countdown timer's duration equals to size of this list. (In seconds)
  messages:
  - '&7Starting in &f5 &7seconds!'
  - '&7Starting in &f4 &7seconds!'
  - '&7Starting in &f3 &7seconds!'
  - '&7Starting in &f2 &7seconds!'
  - '&7Starting in &f1 &7second!'
  - '&7Duel starting now!'

  # While countdown is running, block launching projectiles. (Examples: Arrow, Enderpearl)
  block-projectile: true

  # While countdown is running, block pvp.
  block-pvp: true

# GUI settings
GUI:
  # Select how many rows should each page of the GUI have.
  # Note: Excludes the last row which contains 'previous page' & 'next page' buttons.
  # Must be in range between 1 - 5, otherwise it'll be set to 5 by default.
  kit-selector: 3
  arena-selector: 2

  # The displayName of the map item in Arena Selector GUI
  # displayName for available arenas
  available-arena-displayname: '&9{NAME}: &aAvailable'
  # displayName for in use arenas
  in-use-arena-displayname: '&9{NAME}: &cIn Use'

# Duel settings
Dueling:
  # If enabled: Allows certain commands to be executed on match winner and loser.
  match-end-commands:
    enabled: false
    commands:
    - 'give {WINNER} diamond 1'
    - 'give {LOSER} dirt 1'

  # If enabled: Players will have another GUI open after selecting kit that displays clickable arenas.
  # They are able to choose which arena they want to play on.
  # If someone else uses the arena while the request is pending,
  # the 'arena in use' message will display and the request will be cancelled.
  allow-arena-selecting: true

  # If enabled: Sends a duel request directly on /duel [player] without a kit selection,
  # Allowing players to use their own inventory for dueling.
  # Note: If you're using this option, make sure to edit the duel messages so players
  # will know they'll be using their own items!
  use-own-inventory: false

  # If enabled: Players must have a cleared inventory to execute the command /duel.
  # Player inventories will be restored on duel end if this value is set to 'false'.
  requires-cleared-inventory: true

  # If enabled: On duel end, players will be teleported to the latest location they were at before the start of the match.
  # Recommended: 'true' if your server type is factions/survival. 'false' if your server type is kitpvp.
  teleport-to-latest-location: false

  # On duel end, winner will be teleported after following amount of seconds to spawn / latest location if enabled.
  delay-until-teleport-on-win: 5

  # If enabled: Allows players to drop item while in duel.
  drop-item: true

  # If enabled: Allows players to pick up item while in duel.
  pick-up-item: true

  # If enabled: All commands will be blocked while in duel.
  # If you wish to whitelist certain commands, add them to 'whitelisted-commands' list.
  block-all-commands: false

  # Commands in the following list will be exempted
  # from getting blocked if 'block-all-commands' is enabled.
  whitelisted-commands:
  - 'msg'
  - 'pm'
  - 'list'
  - 'w'
  - 'r'
  - 'ban'
  - 'kick'
  - 'mute'
  - 'tempban'

  # Commands in the following list will be disabled while in duel.
  # NOTE: If block-all-commands is enabled, this option will not take affect.
  # Recommended: Add all the commands that will allow players to gain advantage while in duel. Examples: /heal, /kit
  # Added most of the known commands to default configuration just to save your time. ;)
  # If you have too many commands, 'block-all-commands' is another way to go.
  disabled-commands:
  - 'heal'
  - 'eheal'
  - 'essentials:heal'
  - 'essentials:eheal'
  - 'kit'
  - 'ekit'
  - 'kits'
  - 'ekits'
  - 'essentials:kit'
  - 'essentials:ekit'
  - 'essentials:kits'
  - 'essentials:ekits'
  - 'enderchest'
  - 'echest'
  - 'eechest'
  - 'eenderchest'
  - 'endersee'
  - 'eendersee'
  - 'ec'
  - 'eec'
  - 'essentials:enderchest'
  - 'essentials:echest'
  - 'essentials:eechest'
  - 'essentials:eenderchest'
  - 'essentials:endersee'
  - 'essentials:eendersee'
  - 'essentials:ec'
  - 'essentials:eec'
  - 'tpaccept'
  - 'etpaccept'
  - 'tpyes'
  - 'etpyes'
  - 'essentials:tpaccept'
  - 'essentials:etpaccept'
  - 'essentials:tpyes'
  - 'essentials:etpyes'
  - 'tpahere'
  - 'etpahere'
  - 'essentials:tpahere'
  - 'essentials:etpahere'
  - 'back'
  - 'eback'
  - 'return'
  - 'ereturn'
  - 'essentials:back'
  - 'essentials:eback'
  - 'essentials:return'
  - 'essentials:ereturn'
  - 'sethome'
  - 'esethome'
  - 'createhome'
  - 'ecreatehome'
  - 'essentials:sethome'
  - 'essentials:esethome'
  - 'essentials:createhome'
  - 'essentials:ecreatehome'
  - 'spawn'
  - 'espawn'
  - 'essentials:spawn'
  - 'essentials:espawn'
  - 'vault'
  - 'chest'
  - 'pv'
  - 'playervaults'
  - 'playervaults:vault'
  - 'playervaults:chest'
  - 'playervaults:pv'
  - 'playervaults:playervaults'

# DuelZone settings. Requires WorldGuard!
DuelZone:
  # If enabled: Player must be inside of the region declared below to execute the command /duel.
  enabled: false
  region: spawn

# Stats command settings
Stats:
  # If enabled: Displays a list of data of the player's 10 latest matches when /stats is executed.
  display-matches: true

# Edit messages here! Read the comments above the messages for more information.
Messages:
  # Displayed when player executes the command: /stats
  # Placeholders:
  # {NAME} - Name of the stats owner.
  # {WINS} - Amount of duel wins.
  # {LOSSES} - Amount of duel losses.
  # {REQUESTS_ENABLED} - Displays 'enabled' if player has duel requests enabled, else 'disabled'.
  stats:
    - '&7Displaying stats of &f{NAME} &7-'
    - '&71v1 Wins: &f{WINS}'
    - '&71v1 Losses: &f{LOSSES}'
    - '&71v1 Requests: &f{REQUESTS_ENABLED}'
    - '&7Latest 1v1 matches -'

  # Displayed after the list above if 'display-matches' is enabled.
  # Placeholders:
  # {WINNER} - Name of the winner.
  # {LOSER} - Name of the loser.
  match-format: '&a{WINNER} &fvs &c{LOSER} &6[Hover Me!]'

  # Displayed when hovering the message above.
  # Placeholders:
  # {DURATION} - Formatted match duration.
  # {TIME} - Time since the happening of the match.
  # {HEALTH} - Winner's health.
  # {NEWLINE} - Moves on to the next line.
  match-hover: '&7Duration: &f{DURATION}{NEWLINE}&7Time: &f{TIME} ago{NEWLINE}&7Health: &d&l{HEALTH} ♥'

  # Displayed when player sends a duel request.
  # Placeholders:
  # {PLAYER} - Receiver's name for 'on-request-send', Sender's name for 'on-request-receive'.
  # {KIT} - Name of the kit selected on request send.
  # {ARENA} - 'random' if arena selecting is disabled, selected arena's name if enabled.
  on-request-send: '&9[Duels] &7Duel request sent to &f{PLAYER} &7with kit &f{KIT}&7 on arena &f{ARENA}&7.'
  on-request-receive: '&9[Duels] &7Duel request received from &f{PLAYER} &7with kit &f{KIT}&7 on arena &f{ARENA}&7. Type &f/duel accept {PLAYER} &7to accept. &e[Expires in 30s]'

  # Displayed when a duel ends.
  # {WINNER} - Winner's name.
  # {LOSER} - Loser's name.
  # {HEALTH} - Winner's health.
  on-duel-end: '&9[Duels] &f{WINNER} &7has defeated &f{LOSER} &7with &d&l{HEALTH} ♥'

  # Displayed when player accepts a duel request.
  # Placeholders:
  # {PLAYER} - Request acceptor's name for 'on-request-accept-target', sender's name for 'on-request-accept-sender'.
  # {KIT} - Name of the kit selected on request send.
  # {ARENA} - 'random' if arena selecting is disabled, selected arena's name if enabled.
  on-request-accept-target: '&9[Duels] &7Accepted duel request from &f{PLAYER}&7. Starting match with kit &f{KIT}&7 on arena &f{ARENA}&7.'
  on-request-accept-sender: '&9[Duels] &7Your duel request to &f{PLAYER} &7was accepted. Starting match with kit &f{KIT}&7 on arena &f{ARENA}&7.'

  # Displayed when player accepts a duel request.
  # Placeholders:
  # {PLAYER} - Request acceptor's name for 'on-request-accept-target', sender's name for 'on-request-accept-sender'.
  on-request-deny-target: '&9[Duels] &7Denied duel request from &f{PLAYER}&7.'
  on-request-deny-sender: '&9[Duels] &7Your duel request to &f{PLAYER} &7was denied.'

  # Displayed when player executes the command: /toggle
  # Placeholders: none
  on-requests-enable: '&a&lOthers may send you duel requests from now on.'
  on-requests-disable: '&c&lOthers may not send you duel requests from now on.'

  # Displayed when player executes the command: /duel
  duel-command-usage: 'Send, accept, or deny a duel request.{NEWLINE}/duel [player]{NEWLINE}/duel [accept | deny] [player]'
